"use client";
import { useEffect, useRef, useState } from "react";
import { api, fetchDocumentBlob, post, type CaseView, type Draft } from "@/lib/api";
import { Badge, Button, Card, Empty, KV, fmtDate } from "@/components/ui";

// ------------------------------------------------------------------ Drafts (human-in-the-loop)
export function DraftPanel({ c, onChange, say, perms }: { c: CaseView; onChange: () => void; say: (m: string, k?: "ok" | "err") => void; perms: string[] }) {
  const [editing, setEditing] = useState<Draft | null>(null);
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [lang, setLang] = useState("en");
  const [busy, setBusy] = useState(false);
  const canApprove = perms.includes("approve_send");

  const gen = async () => { setBusy(true); try { await post(`/cases/${c.id}/draft`, { language: lang }); say("Draft generated (not sent)"); onChange(); } catch (e: any) { say(e.message, "err"); } finally { setBusy(false); } };
  const act = async (path: string, d: Draft, extra: any = {}) => { setBusy(true); try { await post(`/cases/${c.id}/${path}`, { draft_id: d.id, ...extra }); say("Done"); setEditing(null); onChange(); } catch (e: any) { say(e.message, "err"); } finally { setBusy(false); } };

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center gap-2 text-xs">
        <Button kind="primary" disabled={busy} onClick={gen}>Generate draft</Button>
        <select value={lang} onChange={(e) => setLang(e.target.value)} className="rounded-md border border-ink-200 px-2 py-1"><option value="en">English</option><option value="zh">Chinese</option><option value="ms">Malay</option><option value="id">Indonesian</option><option value="vi">Vietnamese</option><option value="ko">Korean</option><option value="ar">Arabic</option></select>
        <span className="text-ink-500">AI proposes → you review/edit → {canApprove ? "you approve" : "a supervisor approves"} → send. Nothing is auto-sent.</span>
        {!c.action_required && <Badge className="bg-ink-100 text-ink-700">No reply needed</Badge>}
      </div>
      {c.drafts.length === 0 && <Empty text={c.action_required ? "No draft yet. Click Generate draft." : "Informational case — no reply needed. Generate a draft only if you want to respond."} />}
      {[...c.drafts].reverse().map((d) => (
        <Card key={d.id} title={<span>{d.draft_type.replace(/_/g, " ")} · v{d.version} <Badge className={{ PROPOSED: "bg-accent-bg text-accent-fg", EDITED: "bg-review-bg text-review-fg", APPROVED: "bg-match-bg text-match-fg", DELIVERING: "bg-review-bg text-review-fg", DELIVERY_UNKNOWN: "bg-mismatch-bg text-mismatch-fg", SENT: "bg-match text-white", SIMULATED: "bg-match-bg text-match-fg", SEND_FAILED: "bg-mismatch-bg text-mismatch-fg", REJECTED: "bg-mismatch-bg text-mismatch-fg" }[d.status] || ""}>{d.status}</Badge></span>}
          right={<span className="text-[11px] text-ink-500">generated by {d.generated_by} · evidence: {d.evidence_refs.join(", ") || "—"}</span>}>
          <KV k="To" v={<span className="font-mono text-xs">{d.to.join(", ")}</span>} />
          <KV k="Requires approval" v={d.requires_external_approval ? "Yes — external recipient" : "No"} />
          {editing?.id === d.id ? (
            <div className="mt-2 space-y-2">
              <input value={subject} onChange={(e) => setSubject(e.target.value)} className="w-full rounded-md border border-ink-200 px-2 py-1 text-sm" />
              <textarea value={body} onChange={(e) => setBody(e.target.value)} rows={12} className="w-full rounded-md border border-ink-200 p-2 font-mono text-xs" />
              <div className="flex gap-2"><Button kind="primary" onClick={() => act("draft/edit", d, { edited_subject: subject, edited_body: body })}>Save edit</Button><Button onClick={() => setEditing(null)}>Cancel</Button></div>
            </div>
          ) : (
            <div className="mt-2">
              <div className="text-sm font-medium">{d.subject}</div>
              <pre className="mt-1 whitespace-pre-wrap rounded-md bg-ink-50 p-3 font-mono text-[11px]">{d.body}</pre>
            </div>
          )}
          {d.status !== "SENT" && d.status !== "SIMULATED" && d.status !== "REJECTED" && editing?.id !== d.id && (
            <div className="mt-2 flex flex-wrap gap-2">
              <Button onClick={() => { setEditing(d); setSubject(d.subject); setBody(d.body); }}>Edit</Button>
              <Button kind="success" disabled={!canApprove || busy} title={canApprove ? "Approve and send" : "Requires SUPERVISOR/ADMIN"} onClick={() => act("approve", d)}>Approve & send</Button>
              <Button kind="danger" disabled={busy} onClick={() => act("reject", d, { note: "Rejected by reviewer" })}>Reject</Button>
            </div>
          )}
        </Card>
      ))}
    </div>
  );
}

// ------------------------------------------------------------------ Ask AI
const SUGGESTED = ["Why is this a mismatch?", "Which six fields match?", "Show the SI evidence", "Who is the Notify Party?", "Who should review this?", "Summarize this case", "Draft a correction email", "What changed since the last review?", "Translate this email to Chinese", "What policy applies?"];

function askStarters(c: CaseView): string[] {
  const first: string[] = [];
  if (!c.si_available || !c.bl_available) first.push("What's missing from the documents?");
  if (c.mismatch_count > 0) first.push("Why is this a mismatch?", "Which six fields match?", "Who is the Notify Party?");
  else first.push("Summarize this case", "Which six fields match?", "What policy applies?");
  first.push("Who should review this?", "Draft a correction email", "Show the SI evidence", "What changed since the last review?", "Translate this email to Chinese");
  return [...new Set([...first, ...SUGGESTED])].slice(0, 8);
}

type AskTurn = { q: string; a: { answer: string; citations: { kind: string; ref: string; snippet?: string }[]; grounded: boolean; refused: boolean; generated_by: string } | null };

export function AskPanel({ c, say }: { c: CaseView; say: (m: string, k?: "ok" | "err") => void }) {
  const [q, setQ] = useState("");
  const [log, setLog] = useState<AskTurn[]>([]);
  const [busy, setBusy] = useState(false);
  const [openCite, setOpenCite] = useState<string | null>(null);
  const [copied, setCopied] = useState<number | null>(null);
  const endRef = useRef<HTMLDivElement>(null);
  const boxRef = useRef<HTMLTextAreaElement>(null);
  const starters = askStarters(c);

  useEffect(() => { setLog([]); setQ(""); setBusy(false); setOpenCite(null); }, [c.id]);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [log, busy]);

  const resize = (el: HTMLTextAreaElement | null) => {
    if (!el) return;
    el.style.height = "auto";
    el.style.height = `${Math.min(el.scrollHeight, 140)}px`;
  };

  const ask = async (question: string) => {
    const text = question.trim();
    if (!text || busy) return;
    setBusy(true); setQ(""); setOpenCite(null);
    if (boxRef.current) { boxRef.current.style.height = "auto"; }
    setLog((l) => [...l, { q: text, a: null }]);
    try {
      const a = await post(`/cases/${c.id}/ask`, { question: text });
      setLog((l) => { const next = [...l]; next[next.length - 1] = { q: text, a }; return next; });
    } catch (e: any) {
      setLog((l) => l.slice(0, -1));
      say(e.message, "err");
    } finally { setBusy(false); }
  };

  const copyAnswer = async (i: number, text: string) => {
    try { await navigator.clipboard.writeText(text); setCopied(i); setTimeout(() => setCopied(null), 1600); }
    catch { say("Could not copy", "err"); }
  };

  return (
    <div className="flex min-h-[calc(100dvh-5.5rem)] min-w-0 flex-col overflow-hidden rounded-2xl border border-ink-200 bg-white/95 shadow-card lg:h-[min(40rem,calc(100dvh-8rem))] lg:min-h-0">
      <header className="flex shrink-0 flex-wrap items-start justify-between gap-2 border-b border-ink-100 px-3 py-2.5 sm:px-4">
        <div className="min-w-0">
          <div className="text-sm font-semibold text-ink-900">Ask this case</div>
          <p className="mt-0.5 max-w-[62ch] text-[11px] leading-relaxed text-ink-500">Answers use only this email, SI, Draft BL, comparison, audit and policy. Every reply cites evidence. Nothing is sent from here.</p>
        </div>
        <div className="flex flex-wrap items-center gap-1.5">
          {c.mismatch_count > 0 ? <Badge className="bg-mismatch-bg text-mismatch-fg">{c.mismatch_count} mismatch{c.mismatch_count === 1 ? "" : "es"}</Badge> : <Badge className="bg-match-bg text-match-fg">No mismatch</Badge>}
          <Badge className={c.si_available ? "bg-ink-100 text-ink-700" : "bg-review-bg text-review-fg"}>SI {c.si_available ? "ready" : "missing"}</Badge>
          <Badge className={c.bl_available ? "bg-ink-100 text-ink-700" : "bg-review-bg text-review-fg"}>BL {c.bl_available ? "ready" : "missing"}</Badge>
          {log.length > 0 && <Button kind="ghost" disabled={busy} onClick={() => { setLog([]); setOpenCite(null); }}>Clear</Button>}
        </div>
      </header>

      <div className="min-h-0 flex-1 space-y-3 overflow-y-auto overscroll-contain p-3 scrollbar-thin sm:p-4" aria-live="polite">
        {log.length === 0 && (
          <div className="rounded-xl border border-dashed border-ink-200 bg-ink-50/70 p-3 sm:p-4">
            <div className="text-sm font-semibold text-ink-800">Try a question</div>
            <p className="mt-1 text-xs text-ink-500">Tap a suggestion or type your own. Long questions are fine — Enter sends, Shift+Enter makes a new line.</p>
            <div className="mt-3 flex flex-wrap gap-1.5">
              {starters.map((s) => (
                <button key={s} type="button" disabled={busy} onClick={() => ask(s)} className="rounded-full border border-ink-200 bg-white px-3 py-1.5 text-left text-xs text-ink-800 transition hover:border-accent hover:text-accent-fg disabled:opacity-50">
                  {s}
                </button>
              ))}
            </div>
          </div>
        )}
        {log.map((m, i) => (
          <div key={`${m.q}-${i}`} className="space-y-2">
            <div className="ml-auto max-w-[min(100%,36rem)] break-words rounded-2xl rounded-br-md bg-ink-900 px-3 py-2 text-sm text-white">{m.q}</div>
            {m.a ? (
              <div className={`max-w-[min(100%,40rem)] rounded-2xl rounded-bl-md border px-3 py-2.5 text-sm ${m.a.refused ? "border-review/50 bg-review-bg" : "border-ink-200 bg-ink-50"}`}>
                <pre className="whitespace-pre-wrap break-words font-sans leading-relaxed text-ink-900">{m.a.answer}</pre>
                <div className="mt-2 space-y-1.5">
                  <div className="flex flex-wrap gap-1.5">
                    {(m.a.citations || []).map((ct, j) => {
                      const id = `${i}-${j}`;
                      const open = openCite === id;
                      return (
                        <button key={id} type="button" title={ct.snippet || ct.ref} onClick={() => setOpenCite(open ? null : id)} className={`max-w-full truncate rounded-md border px-1.5 py-0.5 font-mono text-[10px] ${open ? "border-accent bg-accent-bg text-accent-fg" : "border-ink-200 bg-white text-ink-600"}`}>
                          {ct.kind}:{String(ct.ref).slice(0, 18)}
                        </button>
                      );
                    })}
                  </div>
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-[10px] text-ink-400">{m.a.generated_by} · {m.a.grounded ? "grounded" : "ungrounded"}{m.a.refused ? " · refused" : ""}</span>
                    <button type="button" onClick={() => copyAnswer(i, m.a!.answer)} className="shrink-0 text-[10px] font-semibold text-accent-fg hover:underline">{copied === i ? "Copied" : "Copy"}</button>
                  </div>
                </div>
                {m.a.citations.find((_, j) => openCite === `${i}-${j}`)?.snippet && (
                  <p className="mt-2 rounded-lg bg-white px-2 py-1.5 text-[11px] leading-relaxed text-ink-600">{m.a.citations.find((_, j) => openCite === `${i}-${j}`)?.snippet}</p>
                )}
              </div>
            ) : (
              <div className="w-fit rounded-2xl rounded-bl-md border border-ink-200 bg-ink-50 px-3 py-2.5" aria-label="Assistant is answering">
                <span className="flex gap-1">
                  <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-ink-400 [animation-delay:-0.2s]" />
                  <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-ink-400 [animation-delay:-0.1s]" />
                  <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-ink-400" />
                </span>
              </div>
            )}
          </div>
        ))}
        <div ref={endRef} />
      </div>

      {log.length > 0 && (
        <div className="shrink-0 border-t border-ink-100 px-3 pt-2 sm:px-4">
          <div className="flex gap-1.5 overflow-x-auto pb-2 scrollbar-thin sm:flex-wrap sm:overflow-visible">
            {starters.slice(0, 6).map((s) => (
              <button key={s} type="button" disabled={busy} onClick={() => ask(s)} className="shrink-0 rounded-full border border-ink-200 bg-white px-2.5 py-1 text-[11px] text-ink-700 hover:border-accent hover:text-accent-fg disabled:opacity-50">
                {s}
              </button>
            ))}
          </div>
        </div>
      )}

      <form onSubmit={(e) => { e.preventDefault(); ask(q); }} className="shrink-0 border-t border-ink-100 p-3 sm:p-4">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-end">
          <label className="sr-only" htmlFor="ask-ai-input">Question about this case</label>
          <textarea
            id="ask-ai-input"
            ref={boxRef}
            rows={1}
            value={q}
            disabled={busy}
            onChange={(e) => { setQ(e.target.value); resize(e.target); }}
            onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); ask(q); } }}
            placeholder="Ask about this case…"
            className="max-h-36 min-h-[2.6rem] w-full resize-none rounded-xl border border-ink-200 bg-white px-3 py-2.5 text-sm text-ink-900 placeholder:text-ink-400 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent-ring/60 disabled:bg-ink-50"
          />
          <Button type="submit" kind="primary" disabled={busy || !q.trim()} className="w-full sm:w-auto sm:px-4">Ask</Button>
        </div>
        <p className="mt-1.5 hidden text-[10px] text-ink-400 sm:block">Enter to send · Shift+Enter for a new line</p>
      </form>
    </div>
  );
}

// ------------------------------------------------------------------ Email (original / translated / side-by-side)
export function EmailPanel({ c }: { c: CaseView }) {
  const [mode, setMode] = useState<"original" | "translated" | "side">("original");
  const [target, setTarget] = useState("en");
  const [tr, setTr] = useState<string | null>(null);
  const e = c.email!;
  const translate = async () => { const r = await post(`/cases/${c.id}/translate`, { target }); setTr(r.translated); };
  return (
    <div className="min-w-0 space-y-3">
      <div className="grid min-w-0 gap-1 rounded-lg bg-ink-50 p-3 text-sm">
        <KV k="From" v={<span className="font-mono text-xs">{e.sender}</span>} /><KV k="Subject" v={e.subject} /><KV k="Received" v={fmtDate(e.received_at)} />
        <KV k="Message ID" v={<span className="font-mono text-xs">{e.id}</span>} /><KV k="Language" v={e.language} /><KV k="Attachments" v={e.attachments.length} />
      </div>
      <div className="flex flex-wrap items-center gap-2 text-xs">
        {(["original", "translated", "side"] as const).map((m) => <Button key={m} kind={mode === m ? "primary" : "default"} onClick={() => setMode(m)}>{m === "side" ? "Side-by-side" : m[0].toUpperCase() + m.slice(1)}</Button>)}
        <select value={target} onChange={(e) => setTarget(e.target.value)} className="rounded-md border border-ink-200 px-2 py-1"><option value="en">English</option><option value="zh">Chinese</option><option value="ms">Malay</option><option value="id">Indonesian</option><option value="vi">Vietnamese</option><option value="ko">Korean</option><option value="ar">Arabic</option></select>
        <Button onClick={translate}>Translate</Button><span className="text-ink-400">stored original is never replaced</span>
      </div>
      <div className={`grid gap-3 ${mode === "side" ? "md:grid-cols-2" : ""}`}>
        {(mode !== "translated") && <pre className="max-w-full overflow-x-auto whitespace-pre-wrap break-words rounded-lg border border-ink-200 bg-white p-3 font-mono text-xs sm:p-4">{e.body}</pre>}
        {(mode !== "original") && <pre className="max-w-full overflow-x-auto whitespace-pre-wrap break-words rounded-lg border border-accent/40 bg-accent-bg/20 p-3 font-mono text-xs sm:p-4">{tr ?? "Click Translate."}</pre>}
      </div>
    </div>
  );
}

// ------------------------------------------------------------------ Attachments
export function AttachmentsPanel({ c, onChange, say }: { c: CaseView; onChange: () => void; say: (m: string, k?: "ok" | "err") => void }) {
  const [open, setOpen] = useState<string | null>(null);
  const [texts, setTexts] = useState<Record<string, string>>({});
  const [kind, setKind] = useState("BL");
  const fileRef = useRef<HTMLInputElement>(null);
  const upload = async () => {
    const f = fileRef.current?.files?.[0]; if (!f) return say("Choose a file", "err");
    const fd = new FormData(); fd.append("file", f); fd.append("kind", kind);
    try { await api(`/cases/${c.id}/upload`, { method: "POST", body: fd }); say("Uploaded — pipeline re-run"); onChange(); } catch (e: any) { say(e.message, "err"); }
  };
  type Viewer = { id: string; name: string; url: string; mediaType: string; text?: string; note?: string };
  const [viewer, setViewer] = useState<Viewer | null>(null);
  const [loadingDoc, setLoadingDoc] = useState<string | null>(null);
  useEffect(() => () => { if (viewer?.url) URL.revokeObjectURL(viewer.url); }, [viewer]);
  const isText = (mt: string, name: string) => /^text\/|\/csv|rfc822|\/rtf|tab-separated/.test(mt) || /\.(txt|csv|tsv|md|eml|rtf|html?)$/i.test(name);
  const download = (blob: Blob, name: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = name; document.body.appendChild(a); a.click(); a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 10000);
  };
  const openOriginal = async (id: string, mode: "view" | "download") => {
    if (mode === "view" && viewer?.id === id) { setViewer(null); return; }
    setLoadingDoc(id);
    try {
      const { blob, filename, mediaType } = await fetchDocumentBlob(c.id, id);
      const name = filename === "attachment" ? (atts.find((a) => a.id === id)?.file_name || filename) : filename;
      if (mode === "download") { download(blob, name); return; }
      const mt = mediaType.split(";")[0].trim();
      if (mt === "application/pdf" || mt.startsWith("image/")) {
        setViewer({ id, name, url: URL.createObjectURL(blob), mediaType: mt });
      } else if (isText(mt, name)) {
        setViewer({ id, name, url: URL.createObjectURL(blob), mediaType: "text/plain", text: await blob.text() });
      } else {
        download(blob, name);
        setViewer({ id, name, url: "", mediaType: mt, note: "Office files open in your desktop app — the download has started. The extracted text is available with 'Extracted text'." });
      }
    } catch (e: any) { say(e?.detail?.error || e.message || "Could not load the original file", "err"); }
    finally { setLoadingDoc(null); }
  };
  const viewText = async (id: string) => {
    if (open === id) { setOpen(null); return; }
    setOpen(id);
    const att = (c.email?.attachments || []).find((a) => a.id === id);
    if (att?.raw_text) { setTexts((t) => ({ ...t, [id]: att.raw_text as string })); return; }
    if (texts[id] !== undefined) return;
    try {
      const d = await api<{ raw_text: string | null }>(`/cases/${c.id}/documents/${id}`);
      setTexts((t) => ({ ...t, [id]: d.raw_text || "" }));
    } catch { setTexts((t) => ({ ...t, [id]: "" })); }
  };
  const atts = c.email?.attachments || [];
  return (
    <div className="space-y-3">
      {atts.length === 0 && <Empty text="No attachments on this email." />}
      <div className="max-w-full overflow-x-auto"><table className="w-full min-w-[760px] text-xs">
        <thead className="text-[11px] uppercase text-ink-500"><tr><th className="py-1 text-left">File</th><th className="text-left">Type</th><th className="text-left">Detected as</th><th className="text-left">Extraction</th><th className="text-left">Size / checksum</th><th /></tr></thead>
        <tbody>{atts.map((a) => (
          <tr key={a.id} className="border-t border-ink-100">
            <td className="py-1.5 font-mono">{a.file_name}{a.id === c.si_document_id && <Badge className="ml-1 bg-accent-bg text-accent-fg">SI used</Badge>}{a.id === c.bl_document_id && <Badge className="ml-1 bg-accent-bg text-accent-fg">BL used</Badge>}</td>
            <td>{a.file_type}</td>
            <td>{a.detected_type.replace(/_/g, " ")} <span className="text-ink-400">({a.detection_confidence.toFixed(2)})</span></td>
            <td><Badge className={a.extraction_status === "EXTRACTED" ? "bg-match-bg text-match-fg" : "bg-mismatch-bg text-mismatch-fg"}>{a.extraction_status}</Badge> {a.extraction_confidence > 0 && <span className="text-ink-400">{a.extraction_confidence.toFixed(2)}</span>}{a.ocr && <div className="text-[10px] text-review" title={a.reader_note || ""}>text via OCR (lower confidence)</div>}{!a.ocr && a.reader_note && a.extraction_status !== "EXTRACTED" && <div className="text-[10px] text-ink-500">{a.reader_note}</div>}{a.is_duplicate_of && <div className="text-[10px] text-review">duplicate of {a.is_duplicate_of}</div>}</td>
            <td className="font-mono text-[10px] text-ink-500">{a.size_bytes} B · {a.checksum.slice(0, 12)}…</td>
            <td className="whitespace-nowrap">
              <Button kind="primary" disabled={loadingDoc === a.id} onClick={() => openOriginal(a.id, "view")}>{loadingDoc === a.id ? "Loading…" : viewer?.id === a.id ? "Close" : "Open"}</Button>{" "}
              <Button kind="ghost" disabled={loadingDoc === a.id} onClick={() => openOriginal(a.id, "download")}>Download</Button>{" "}
              <Button kind="ghost" onClick={() => viewText(a.id)}>{open === a.id ? "Hide extracted text" : "Extracted text"}</Button>
            </td>
          </tr>
        ))}</tbody>
      </table></div>
      {viewer && (
        <div className="overflow-hidden rounded-xl border border-ink-200 bg-white">
          <div className="flex flex-wrap items-center gap-2 border-b border-ink-100 bg-ink-50 px-3 py-2 text-xs">
            <span className="font-mono font-semibold text-ink-900">{viewer.name}</span>
            <span className="text-ink-500">{viewer.mediaType}</span>
            <span className="ml-auto flex gap-2">
              {viewer.url && viewer.mediaType !== "text/plain" && <a className="text-accent-fg hover:underline" href={viewer.url} target="_blank" rel="noreferrer">Open in new tab ↗</a>}
              <button type="button" className="text-ink-500 hover:text-ink-900" onClick={() => setViewer(null)}>Close ×</button>
            </span>
          </div>
          {viewer.mediaType === "application/pdf" && <iframe title={viewer.name} src={viewer.url} className="h-[70vh] w-full bg-ink-100" />}
          {viewer.mediaType.startsWith("image/") && <div className="max-h-[70vh] overflow-auto bg-ink-100 p-3 text-center"><img src={viewer.url} alt={viewer.name} className="mx-auto max-w-full" /></div>}
          {viewer.text !== undefined && <pre className="max-h-[60vh] overflow-auto whitespace-pre-wrap p-3 font-mono text-[11px] scrollbar-thin">{viewer.text || "(empty file)"}</pre>}
          {viewer.note && <p className="px-3 py-3 text-xs text-ink-600">{viewer.note}</p>}
        </div>
      )}
      {open && <pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded-lg border border-ink-200 bg-ink-50 p-3 font-mono text-[11px] scrollbar-thin">{texts[open] || atts.find((a) => a.id === open)?.raw_text || "(no extractable text — unreadable / image-only / empty)"}</pre>}
      <Card title="Upload / re-link a missing document">
        <div className="flex flex-wrap items-center gap-2 text-xs">
          <select value={kind} onChange={(e) => setKind(e.target.value)} className="rounded-md border border-ink-200 px-2 py-1"><option value="SI">Shipping Instruction</option><option value="BL">Draft BL</option><option value="auto">Auto-detect</option></select>
          <input ref={fileRef} type="file" accept=".txt,.pdf,.docx,.xlsx" className="max-w-full text-xs" />
          <Button kind="primary" onClick={upload}>Upload & retry</Button>
          <span className="text-ink-500">Files are parsed to text only — never executed. Blocked types: .exe .bat .js .vbs …</span>
        </div>
      </Card>
    </div>
  );
}

// ------------------------------------------------------------------ Audit
export function AuditPanel({ c }: { c: CaseView }) {
  const [events, setEvents] = useState<any[]>([]);
  const [filter, setFilter] = useState("");
  useEffect(() => { api(`/cases/${c.id}/audit`).then((d) => setEvents(d.events)).catch(() => {}); }, [c.id, c.updated_at]);
  const rows = events.filter((e) => !filter || e.action.includes(filter) || e.actor_type === filter);
  return (
    <div className="space-y-2">
      <div className="flex items-center gap-2 text-xs"><input placeholder="Filter by action or actor (USER/AI/SYSTEM)" value={filter} onChange={(e) => setFilter(e.target.value.toUpperCase())} className="w-72 rounded-md border border-ink-200 px-2 py-1" /><span className="text-ink-500">{rows.length} events · append-only</span></div>
      <div className="overflow-auto rounded-xl border border-ink-200 bg-white scrollbar-thin">
        <table className="w-full text-xs">
          <thead className="bg-ink-50 text-[11px] uppercase text-ink-500"><tr><th className="px-2 py-1.5 text-left">Time</th><th className="px-2 text-left">Actor</th><th className="px-2 text-left">Action</th><th className="px-2 text-left">Before</th><th className="px-2 text-left">After</th><th className="px-2 text-left">Evidence</th><th className="px-2 text-left">Policy</th></tr></thead>
          <tbody>{rows.map((e) => (
            <tr key={e.event_id} className="border-t border-ink-100 align-top">
              <td className="whitespace-nowrap px-2 py-1.5 font-mono text-[10px] text-ink-500">{fmtDate(e.timestamp)}</td>
              <td className="px-2 py-1.5"><Badge className={{ USER: "bg-accent-bg text-accent-fg", AI: "bg-accent-soft text-accent-fg", SYSTEM: "bg-ink-100 text-ink-700" }[e.actor_type as string] || ""}>{e.actor_type}</Badge><div className="text-[10px] text-ink-500">{e.actor_id}</div></td>
              <td className="px-2 py-1.5 font-medium">{e.action}</td>
              <td className="max-w-[220px] px-2 py-1.5 font-mono text-[10px] text-ink-500">{e.before ? JSON.stringify(e.before).slice(0, 160) : ""}</td>
              <td className="max-w-[320px] px-2 py-1.5 font-mono text-[10px] text-ink-700">{e.after ? JSON.stringify(e.after).slice(0, 220) : ""}</td>
              <td className="px-2 py-1.5 font-mono text-[10px] text-ink-500">{e.evidence_ref || ""}</td>
              <td className="px-2 py-1.5 text-[10px] text-ink-500">{e.policy_version}</td>
            </tr>
          ))}</tbody>
        </table>
      </div>
    </div>
  );
}

// ------------------------------------------------------------------ Timeline
const ORDER = ["RECEIVED","SECURITY_CHECK","CLASSIFIED","DOCUMENTS_DETECTED","EXTRACTING","COMPARING","MISMATCH_DETECTED|NO_MISMATCH_DETECTED|WAITING_DOCUMENTS|NO_ACTION_INFO|SECURITY_REVIEW","HUMAN_REVIEW","DRAFT_READY","NOTIFY_PARTY","AWAITING_RESPONSE|ASSIGNED","COMPLETED"];
export function Timeline({ c }: { c: CaseView }) {
  const seen = new Set<string>(["RECEIVED", ...c.trace.map((t) => t.node), c.status]);
  const statusesHit = new Set<string>();
  c.trace.forEach((t) => { if (t.output?.status) statusesHit.add(t.output.status); });
  const stages = ORDER.map((s) => { const opts = s.split("|"); const hit = opts.find((o) => o === c.status) || opts.find((o) => statusesHit.has(o)); return { label: (hit || opts[0]).replace(/_/g, " "), key: s, active: !!hit || (opts.length === 1 && isReached(opts[0], c)) }; });
  const currentLabel = c.status.replace(/_/g, " ");
  const currentIndex = stages.findIndex((s) => s.label === currentLabel);
  const strip = useRef<HTMLDivElement>(null);
  // on phones the strip scrolls sideways: keep the current step in view
  useEffect(() => { strip.current?.querySelector<HTMLElement>("[data-current='true']")?.scrollIntoView({ block: "nearest", inline: "center" }); }, [c.status]);
  return (
    <div className="text-[10px]">
      <div className="mb-1.5 flex items-center justify-between gap-2 text-[11px] sm:hidden">
        <span className="font-semibold text-ink-800">Step {currentIndex + 1} of {stages.length} · <span className="capitalize">{currentLabel.toLowerCase()}</span></span>
      </div>
      <div ref={strip} className="flex snap-x items-center gap-1 overflow-x-auto pb-1 scrollbar-thin sm:flex-wrap sm:overflow-visible sm:pb-0">
        {stages.map((s, i) => (
          <div key={s.key} className="flex shrink-0 snap-start items-center gap-1">
            <span data-current={s.label === currentLabel} className={`whitespace-nowrap rounded-full px-2 py-0.5 ${s.label === currentLabel ? "bg-ink-900 text-white" : s.active ? "bg-accent-bg text-accent-fg" : "bg-ink-100 text-ink-400"}`}>{s.label}</span>
            {i < stages.length - 1 && <span className="text-ink-300">›</span>}
          </div>
        ))}
        <span className="ml-2 hidden whitespace-nowrap text-ink-400 sm:inline">{c.processing_ms} ms pipeline · {seen.size} nodes</span>
      </div>
      <div className="mt-1 text-right text-ink-400 sm:hidden">{c.processing_ms} ms pipeline · {seen.size} nodes</div>
    </div>
  );
}
function isReached(stage: string, c: CaseView): boolean {
  const nodes = c.trace.map((t) => t.node);
  const map: Record<string, boolean> = {
    RECEIVED: true, SECURITY_CHECK: nodes.includes("security_precheck"), CLASSIFIED: nodes.includes("intent_classifier"), DOCUMENTS_DETECTED: nodes.includes("attachment_classifier"),
    EXTRACTING: nodes.includes("document_extractor"), COMPARING: nodes.includes("seven_field_comparator"), HUMAN_REVIEW: ["HUMAN_REVIEW","DRAFT_READY","NOTIFY_PARTY","AWAITING_RESPONSE","ASSIGNED","COMPLETED"].includes(c.status) && c.mismatch_count > 0,
    DRAFT_READY: c.drafts.length > 0, NOTIFY_PARTY: ["NOTIFY_PARTY","AWAITING_RESPONSE"].includes(c.status) || c.shared_with.length > 0, COMPLETED: c.status === "COMPLETED",
  };
  return !!map[stage];
}
